language: scala
scala:
   - 2.11.1
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7

#branches:
#  only:
#    - master
#    - develop

script:
  - "./sbt clean coverage test"
  - "./sbt coverageAggregate"

after_success: "./sbt coveralls"
